// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/approvalpb/supervisor.proto

package approvalpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Supervisor struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Branch               string   `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Supervisor) Reset()         { *m = Supervisor{} }
func (m *Supervisor) String() string { return proto.CompactTextString(m) }
func (*Supervisor) ProtoMessage()    {}
func (*Supervisor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0eb428bdf62ec3d3, []int{0}
}

func (m *Supervisor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Supervisor.Unmarshal(m, b)
}
func (m *Supervisor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Supervisor.Marshal(b, m, deterministic)
}
func (m *Supervisor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supervisor.Merge(m, src)
}
func (m *Supervisor) XXX_Size() int {
	return xxx_messageInfo_Supervisor.Size(m)
}
func (m *Supervisor) XXX_DiscardUnknown() {
	xxx_messageInfo_Supervisor.DiscardUnknown(m)
}

var xxx_messageInfo_Supervisor proto.InternalMessageInfo

func (m *Supervisor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Supervisor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Supervisor) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

type SupervisorRequest struct {
	Supervisor           *Supervisor `protobuf:"bytes,1,opt,name=supervisor,proto3" json:"supervisor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SupervisorRequest) Reset()         { *m = SupervisorRequest{} }
func (m *SupervisorRequest) String() string { return proto.CompactTextString(m) }
func (*SupervisorRequest) ProtoMessage()    {}
func (*SupervisorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0eb428bdf62ec3d3, []int{1}
}

func (m *SupervisorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupervisorRequest.Unmarshal(m, b)
}
func (m *SupervisorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupervisorRequest.Marshal(b, m, deterministic)
}
func (m *SupervisorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupervisorRequest.Merge(m, src)
}
func (m *SupervisorRequest) XXX_Size() int {
	return xxx_messageInfo_SupervisorRequest.Size(m)
}
func (m *SupervisorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SupervisorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SupervisorRequest proto.InternalMessageInfo

func (m *SupervisorRequest) GetSupervisor() *Supervisor {
	if m != nil {
		return m.Supervisor
	}
	return nil
}

type SupervisorResponse struct {
	Result               []*Supervisor `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SupervisorResponse) Reset()         { *m = SupervisorResponse{} }
func (m *SupervisorResponse) String() string { return proto.CompactTextString(m) }
func (*SupervisorResponse) ProtoMessage()    {}
func (*SupervisorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0eb428bdf62ec3d3, []int{2}
}

func (m *SupervisorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupervisorResponse.Unmarshal(m, b)
}
func (m *SupervisorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupervisorResponse.Marshal(b, m, deterministic)
}
func (m *SupervisorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupervisorResponse.Merge(m, src)
}
func (m *SupervisorResponse) XXX_Size() int {
	return xxx_messageInfo_SupervisorResponse.Size(m)
}
func (m *SupervisorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SupervisorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SupervisorResponse proto.InternalMessageInfo

func (m *SupervisorResponse) GetResult() []*Supervisor {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Supervisor)(nil), "approval.Supervisor")
	proto.RegisterType((*SupervisorRequest)(nil), "approval.SupervisorRequest")
	proto.RegisterType((*SupervisorResponse)(nil), "approval.SupervisorResponse")
}

func init() { proto.RegisterFile("pkg/approvalpb/supervisor.proto", fileDescriptor_0eb428bdf62ec3d3) }

var fileDescriptor_0eb428bdf62ec3d3 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0xc8, 0x4e, 0xd7,
	0x4f, 0x2c, 0x28, 0x28, 0xca, 0x2f, 0x4b, 0xcc, 0x29, 0x48, 0xd2, 0x2f, 0x2e, 0x2d, 0x48, 0x2d,
	0x2a, 0xcb, 0x2c, 0xce, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x49, 0x2a,
	0x79, 0x70, 0x71, 0x05, 0xc3, 0x65, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98,
	0xc0, 0x22, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x52, 0x51, 0x62, 0x5e, 0x72, 0x86, 0x04, 0x33,
	0x58, 0x14, 0xca, 0x53, 0xf2, 0xe4, 0x12, 0x44, 0x98, 0x14, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c,
	0x22, 0x64, 0xc2, 0xc5, 0x85, 0xb0, 0x1c, 0x6c, 0x30, 0xb7, 0x91, 0x88, 0x1e, 0xcc, 0x76, 0x3d,
	0x24, 0x0d, 0x48, 0xea, 0x94, 0x9c, 0xb8, 0x84, 0x90, 0x8d, 0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x15, 0xd2, 0xe1, 0x62, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x91, 0x60, 0x54, 0x60, 0xc6, 0x69,
	0x0e, 0x54, 0x8d, 0x51, 0x12, 0xb2, 0x73, 0x82, 0x41, 0x74, 0x72, 0xaa, 0x90, 0x2f, 0x17, 0x9f,
	0x7b, 0x6a, 0x09, 0x42, 0xbc, 0x58, 0x48, 0x1a, 0xab, 0x21, 0x10, 0xd7, 0x4b, 0xc9, 0x60, 0x97,
	0x84, 0xb8, 0x47, 0x89, 0xc1, 0x89, 0x27, 0x8a, 0x0b, 0x11, 0xca, 0x49, 0x6c, 0xe0, 0xb0, 0x35,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x87, 0x69, 0xe4, 0x13, 0x7e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SupervisorServiceClient is the client API for SupervisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SupervisorServiceClient interface {
	GetSupervisors(ctx context.Context, in *SupervisorRequest, opts ...grpc.CallOption) (*SupervisorResponse, error)
}

type supervisorServiceClient struct {
	cc *grpc.ClientConn
}

func NewSupervisorServiceClient(cc *grpc.ClientConn) SupervisorServiceClient {
	return &supervisorServiceClient{cc}
}

func (c *supervisorServiceClient) GetSupervisors(ctx context.Context, in *SupervisorRequest, opts ...grpc.CallOption) (*SupervisorResponse, error) {
	out := new(SupervisorResponse)
	err := c.cc.Invoke(ctx, "/approval.SupervisorService/GetSupervisors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupervisorServiceServer is the server API for SupervisorService service.
type SupervisorServiceServer interface {
	GetSupervisors(context.Context, *SupervisorRequest) (*SupervisorResponse, error)
}

// UnimplementedSupervisorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSupervisorServiceServer struct {
}

func (*UnimplementedSupervisorServiceServer) GetSupervisors(ctx context.Context, req *SupervisorRequest) (*SupervisorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupervisors not implemented")
}

func RegisterSupervisorServiceServer(s *grpc.Server, srv SupervisorServiceServer) {
	s.RegisterService(&_SupervisorService_serviceDesc, srv)
}

func _SupervisorService_GetSupervisors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupervisorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).GetSupervisors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/approval.SupervisorService/GetSupervisors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).GetSupervisors(ctx, req.(*SupervisorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SupervisorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "approval.SupervisorService",
	HandlerType: (*SupervisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupervisors",
			Handler:    _SupervisorService_GetSupervisors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/approvalpb/supervisor.proto",
}
